trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'urban.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
